twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        locales: '%app.locales%'
        interfaceConfiguration: '@App\Service\ConfigurationService'
        uploads: "/uploads"
